<?php

function encrypt_menu() {
    $items = array();
    $items['encrypt'] = array(
        'title' => 'Cipher Encrypt',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('encrypt_form'),
    );
    $items['encrypt_success'] = array(
        'title' => 'Success',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'encrypt_success',
    );
    return $items;
}

function encrypt_form() {
    $form = array();
    $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Enter shift value.'),
            '#element_validate' => array('element_validate_integer_positive'),
            '#required' => TRUE,
    );

    $form['direction'] = array(
        '#title' => 'Direction',
        '#type' => 'textfield',
        '#description' => t('Enter direction of shift.'),
        // '#element_validate' => array('element_direction'),
        '#required' => TRUE,
    );

    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter phrase to be encrypted.'),
        '#element_validate' => array('element_spaces_punctuation'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt it'
    );

    return $form;
}

function element_direction($element) {
  if ($element['#value'] != 'right' || 'left') {
    form_error($element, t('Direction must be specified as right or left only!'));
  }
}

function element_spaces_punctuation($element) {
  if (ctype_alpha(str_replace(array(' ', '.', '!', '?'), '', $element['#value'])) === false ) {
    form_error($element, t('Input can only contain letters, spaces, and punctuation!'));
  }
}

function encrypt_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    $shift_value = $shift_value % 26;
    $direction = strtolower($direction);
    $phrase = strtolower($phrase);
    $letters = str_split($phrase);
    $result = array();
    $encrypted;

    if ($direction === 'left') {
      $shift_value = 26 - $shift_value;
    }

    // if ($shift_value > 26) {
    //   $shift_value = $shift_value - 26;
    // }
    foreach ($letters as $i => $letter) {
      if (ctype_alpha($letter) === true) {
        $result[$i] = chr(97 + (ord($letter) - 97 + $shift_value) % 26);
      }
      else {
        $result[$i] = $letter;
      }
    }

    $encrypted = implode("", $result);

    $_SESSION['encrypted'] = $encrypted;
    $form_state['redirect'] = 'encrypt_success';
}

function encrypt_success() {
    $encrypted = $_SESSION['encrypted'];
    return "you encrypted a phrase! $encrypted";
}
