<?php

function encrypt_menu() {
    $items = array();
    $items['encrypt'] = array(
        'title' => 'Cipher Encrypt',
        'type' => MENU_NORMAL_ITEM,
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('encrypt_form'),
    );
    $items['encrypt_success'] = array(
        'title' => 'Success',
        'type' => MENU_CALLBACK,
        'access callback' => TRUE,
        'page callback' => 'encrypt_success',
    );
    return $items;
}

function encrypt_form() {
    $form = array();
    $form['shift_value'] = array(
            '#title' => 'Shift Value',
            '#type' => 'textfield',
            '#description' => t('Enter shift value.'),
    );

    $form['direction'] = array(
        '#title' => 'Direction',
        '#type' => 'textfield',
        '#description' => t('Enter direction of shift.'),
    );

    $form['phrase'] = array(
        '#title' => 'Phrase',
        '#type' => 'textfield',
        '#description' => t('Enter phrase to be encrypted.'),
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt it'
    );

    return $form;
}

function encrypt_form_submit($form, &$form_state) {
    $shift_value = $form_state['values']['shift_value'];
    $direction = $form_state['values']['direction'];
    $phrase = $form_state['values']['phrase'];
    $direction = strtolower($direction);
    $phrase = strtolower($phrase);
    $letters = str_split($phrase);
    $result = array();
    $encrypted;

    if ($direction === 'left') {
      $shift_value = 26 - $shift_value;
    }

    if ($shift_value > 26) {
      $shift_value = $shift_value - 26;
    }

    foreach ($letters as $index => $let) {
      $result[$index] = chr(97 + (ord($let) - 97 + $shift_value));
    }

    $encrypted = implode("", $result);

    $_SESSION['encrypted'] = $encrypted;
    $form_state['redirect'] = 'encrypt_success';
}

function encrypt_success() {
    $encrypted = $_SESSION['encrypted'];
    return "you encrypted a phrase! $encrypted";
}
